platform :ios, '11.0'

target 'Hackathon' do
  use_frameworks!

  ## Networking
  pod 'Alamofire', '~>4.6.0'
  
  ## UI
  pod 'Reusable', '~>4.0.0'
  pod 'Permission/Location'
  pod 'NVActivityIndicatorView'
  
  ## Utils
  pod 'Marshal'
  pod 'SwiftFormat/CLI'
    
  ## Resources
  pod 'R.swift'
  pod 'UIFontComplete'
  target 'HackathonTests' do
    inherit! :search_paths
  end

  target 'HackathonUITests' do
    inherit! :search_paths
  end

end
